@startuml NetworkSequence

participant Client1 order 0
participant Server order 1 #00AAFF
participant Client2 order 2
participant Client3 order 3


Client2 -> Server : ...
Client3 -> Server : ...

Client1 -> Server: Connect
Client1 -> Server: RegisterNicknameRequest
Client1 <-[#FF0000]- Server: ErrorResponse
Client1 -> Server: RegisterNicknameRequest
Client1 <-[#2fb52f]- Server: AckResponse

Client1 -> Server: ListGamesRequest
Client1 <-- Server: GamesListResponse

Client1 -> Server: JoinGameRequest
Client1 <-[#2fb52f]- Server: AckResponse

Client1 <-[#e6c109]- Server: GameUpdateResponse
Client2 <-[#e6c109]- Server: GameUpdateResponse
Client3 <-[#e6c109]- Server: GameUpdateResponse

Client1 -> Server: PlayAssistantCardRequest
Client1 <-[#2fb52f]- Server: AckResponse
Client1 <-[#e6c109]- Server: GameUpdateResponse
Client2 <-[#e6c109]- Server: GameUpdateResponse
Client3 <-[#e6c109]- Server: GameUpdateResponse

Client2 -> Server: PlayAssistantCardRequest
Client2 <-[#2fb52f]- Server: AckResponse
Client2 <-[#e6c109]- Server: GameUpdateResponse
Client1 <-[#e6c109]- Server: GameUpdateResponse
Client3 <-[#e6c109]- Server: GameUpdateResponse

@enduml
